:toc: macro
image:https://m-m-m.github.io/logo.svg[logo,width="150",link="https://m-m-m.github.io"]

image:https://img.shields.io/github/license/m-m-m/ui-api.svg?label=License["Apache License, Version 2.0",link=https://github.com/m-m-m/ui-api/blob/master/LICENSE]
image:https://travis-ci.com/m-m-m/ui-api.svg?branch=master["build-status",link="https://travis-ci.com/m-m-m/ui-api"]

toc::[]

== mmm-ui-api

The project `mmm-ui-api` provides an abstraction API for user-interfaces (UI).
This allows to build a powerful UI independent of the actual toolkit.
You can write portable UI code that can run

* as native JavaFx application using https://github.com/m-m-m/ui-fx[mmm-ui-fx]
* as web-app in the browser using https://github.com/m-m-m/ui-tvm[mmm-ui-tvm]
* as mobile app for android devices using https://github.com/m-m-m/ui-android[mmm-ui-android]
* as dummy implementation for automated unit tests using https://github.com/m-m-m/ui-test[mmm-ui-test]
* ...in the future we might implement more alternatives such as iOS or SWT

For motivation and details see the https://github.com/m-m-m/ui-api/wiki[wiki] or JavaDoc (click on the badgets below).
In order to implement your client (with UI) you only need to depend on modules from this API.
Therefore, you will typically build a module for your client that is portable.
Dependencies to the implementation of this UI are only needed at runtime.
You can create modules for each toolkit or technology you want support for your client where you add the dependency to the specific implementation and just one or few classes to bind and launch the client. Details how to do that can be found in the documentation of the actual UI implementation or you can have a look at our https://github.com/m-m-m/ui-demo[ui-demo].

== mmm-ui-api-all

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-all.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-ui-api-all/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-ui-api-all]

The module `mmm-ui-api-all` aggregates all other modules of this project.
This allows most simple usage for you while still offering a modularized design.
More advanced or specific users also have the freedom to pick only the API modules they need instead of using all in order to minimize dependent code or even to replace a part of the API with their own code. In such cases read on to the modules below.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-all</artifactId>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.all;
```

== mmm-ui-api-core

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-core.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-ui-api-core/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-ui-api-core]

The module `mmm-ui-api-core` is the core part of the UI API and will always be required. It contains central interfaces like `UiWidget`, `UiScreen`, `UiNotifier`, etc.
You will typically also need `mmm-ui-api-window` together with `mmm-ui-api-core` but all other API modules are optional.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-core</artifactId>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.core;
```

== mmm-ui-api-binding

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-binding.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-ui-api-binding/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-ui-api-binding]

The module `mmm-ui-api-binding` provides powerful databinding and generic form creation for `mmm-property` and `mmm-bean`. It save you from lots of work and boost your productivity to sky-rocket development.
See the JavaDoc link for further details.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-binding</artifactId>
</dependency>
```
Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.binding;
```

== mmm-ui-api-breadcrumb

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-breadcrumb.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-ui-api-breadcrumb/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-ui-api-breadcrumb]

The module `mmm-ui-api-breadcrumb` provides support for a breadcrumb bar.
See the JavaDoc link for further details.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-breadcrumb</artifactId>
</dependency>
```
Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.breadcrumb;
```

== mmm-ui-api-chart

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-chart.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-ui-api-chart/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-ui-api-chart]

The module `mmm-ui-api-chart` provides support for charts like `UiBarChart`, `UiPieChart`, etc. to enrich your UI with powerful data visualization.
See the JavaDoc link for further details.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-chart</artifactId>
</dependency>
```
Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.chart;
```

== mmm-ui-api-controller

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-controller.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-ui-api-controller/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-ui-api-controller]

The module `mmm-ui-api-controller` provides support for navigation (routing) via a simple but powerful MVC approach.
You only need to implement a minimal controler per view to make your client modular, maintainable, and flexible.
See the JavaDoc link for further details.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-controller</artifactId>
</dependency>
```
Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.controller;
```

== mmm-ui-api-data

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-data.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-ui-api-data/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-ui-api-data]

The module `mmm-ui-api-data` provides complex and advanced data-widgets such as `UiDataTable`, `UiDataTree`, and `UiDataTreeTable` to display and navigate on larger sets of data.
See the JavaDoc link for further details.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-data</artifactId>
</dependency>
```
Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.data;
```

== mmm-ui-api-form

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-form.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-ui-api-form/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-ui-api-form]

The module `mmm-ui-api-form` provides composite widgets like `UiFormPanel` or `UiFormGroup` to build forms to edit data.
See the JavaDoc link for further details.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-form</artifactId>
</dependency>
```
Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.form;
```

== mmm-ui-api-format

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-format.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-ui-api-format/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-ui-api-format]

The module `mmm-ui-api-format` provides widgets like `UiHtmlEditor` or `UiSourceCodeViewer` to display or edit struturally formatted text.
See the JavaDoc link for further details.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-format</artifactId>
</dependency>
```
Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.format;
```

== mmm-ui-api-media

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-media.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-ui-api-media/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-ui-api-media]

The module `mmm-ui-api-media` provides widgets like `UiAudioPlayer` or `UiVideoPlayer` to play multimedia data.
See the JavaDoc link for further details.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-media</artifactId>
</dependency>
```
Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.media;
```

== mmm-ui-api-menu

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-menu.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-ui-api-menu/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-ui-api-menu]

The module `mmm-ui-api-menu` provides widgets like `UiMenuBar` to offer a menu bar for quick access to central functionality.
See the JavaDoc link for further details.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-menu</artifactId>
</dependency>
```
Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.menu;
```

== mmm-ui-api-number

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-number.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-ui-api-number/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-ui-api-number]

The module `mmm-ui-api-number` provides input widgets to edit all kind of numbers or numeric datatypes (`UiIntegerInput`, `UiIntegerSlider`, `UiBigDecimalInput`, etc.).
See the JavaDoc link for further details.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-number</artifactId>
</dependency>
```
Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.number;
```

== mmm-ui-api-tab

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-tab.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-ui-api-tab/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-ui-api-tab]

The module `mmm-ui-api-tab` provides widget such as `UiTabPanel` and `UiTab` to create complex panels that are structured via tabs.
See the JavaDoc link for further details.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-tab</artifactId>
</dependency>
```
Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.tab;
```

== mmm-ui-api-temporal

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-temporal.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-ui-api-temporal/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-ui-api-temporal]

The module `mmm-ui-api-temporal` provides input widgets to edit all kind of temporal datatypes like `UiTimeInput`, `UiDateInput`, and `UiDateTimeInput`.
The API is based on Java's modern `java.time` datatypes.
See the JavaDoc link for further details.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-temporal</artifactId>
</dependency>
```
Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.temporal;
```

== mmm-ui-api-window

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-window.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-ui-api-window/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-ui-api-window]

The module `mmm-ui-api-window` provides widgets for windows like `UiMainWindow`, `UiPopup`, and `UiWindow`.
See the JavaDoc link for further details.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-window</artifactId>
</dependency>
```
Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.window;
```
