image:https://m-m-m.github.io/logo.svg[logo,width="150",link="https://m-m-m.github.io"]

image:https://img.shields.io/github/license/m-m-m/ui-api.svg?label=License["Apache License, Version 2.0",link=https://github.com/m-m-m/ui-api/blob/master/LICENSE]
image:https://travis-ci.org/m-m-m/ui-api.svg?branch=master["build-status",link="https://travis-ci.org/m-m-m/ui-api"]

== mmm-ui-api

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-all.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://m-m-m.github.io/javadoc.svg?status=online["apidoc",link="https://m-m-m.github.io/docs/api/io.github.mmm.ui.api.core/module-summary.html"]

The module `mmm-ui-api` provides an abstraction API for user-interfaces (UI).
This allows to build a powerful UI independent of the actual toolkit.
You can write portable UI code that can run

* as native JavaFx application using https://github.com/m-m-m/ui-fx[mmm-ui-fx]
* as web-app in the browser using https://github.com/m-m-m/ui-tvm[mmm-ui-tvm]
* as mobile app for android devices using https://github.com/m-m-m/ui-android[mmm-ui-android]
* as dummy implementation for automated unit tests using https://github.com/m-m-m/ui-test[mmm-ui-test]
* ...in the future we might implement more alternatives such as iOS or SWT

For motivation and details see the https://m-m-m.github.io/docs/api/io.github.mmm.ui.api.core/module-summary.html[documnetation].

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-all</artifactId>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.all;
```

== mmm-ui-api-binding

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-api-binding.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://m-m-m.github.io/javadoc.svg?status=online["apidoc",link="https://m-m-m.github.io/docs/api/io.github.mmm.ui.api.binding/module-summary.html"]

The module `mmm-ui-api-binding` provides powerful databinding and generic form creation for `mmm-property` and `mmm-bean`. Save lots of work and boost your productivity to sky-rocket development.
See the JavaDoc link for further details.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-api-binding</artifactId>
</dependency>
```
Module Dependency:
```java
  requires transitive io.github.mmm.ui.api.binding;
```
