image:https://m-m-m.github.io/logo.svg[logo,width="150",link="https://m-m-m.github.io"]

image:https://img.shields.io/github/license/m-m-m/ui.svg?label=License["Apache License, Version 2.0",link=https://github.com/m-m-m/ui/blob/master/LICENSE]
image:https://travis-ci.org/m-m-m/ui.svg?branch=master["build-status",link="https://travis-ci.org/m-m-m/ui"]

== mmm-ui

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://m-m-m.github.io/javadoc.svg?status=online["apidoc",link="https://m-m-m.github.io/docs/api/io.github.mmm.ui/module-summary.html"]

The module `mmm-ui` provides an abstraction API for user-interfaces (UI).
This allows to build a powerful UI independent of the actual toolkit.
You can write portable UI code that can run

* as native JavaFx application
* as web-app in the browser
* ...in the future we might implement more alternatives such as android or SWT

For motivation and details see the https://m-m-m.github.io/docs/api/io.github.mmm.ui/module-summary.html[documnetation].

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui</artifactId>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.ui;
```

== mmm-ui-binding

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-ui-binding.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://m-m-m.github.io/javadoc.svg?status=online["apidoc",link="https://m-m-m.github.io/docs/api/io.github.mmm.ui.binding/module-summary.html"]

The module `mmm-ui-binding` provides powerful databinding and generic form creation for `mmm-property` and `mmm-bean`. Save lots of work and boost your productivity to sky-rocket development.
See the JavaDoc link for further details.

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-ui-binding</artifactId>
</dependency>
```
Module Dependency:
```java
  requires transitive io.github.mmm.ui.binding;
```
