image:https://m-m-m.github.io/logo.svg[logo,width="150",link="https://m-m-m.github.io"]

image:https://img.shields.io/github/license/m-m-m/ui-api.svg?label=License["Apache License, Version 2.0",link=https://github.com/m-m-m/ui-api/blob/master/LICENSE]
image:https://travis-ci.com/m-m-m/ui-api.svg?branch=master["build-status",link="https://travis-ci.com/m-m-m/ui-api"]

== mmm-ui-api

The project `mmm-ui-api` provides an abstraction API for user-interfaces (UI).
This allows to build a powerful UI independent of the actual toolkit.
You can write portable UI code that can run

* as native JavaFx application using https://github.com/m-m-m/ui-fx[mmm-ui-fx]
* as web-app in the browser using https://github.com/m-m-m/ui-tvm[mmm-ui-tvm]
* as mobile app for android devices using https://github.com/m-m-m/ui-android[mmm-ui-android]
* as dummy implementation for automated unit tests using https://github.com/m-m-m/ui-test[mmm-ui-test]
* ...in the future we might implement more alternatives such as iOS or SWT

For motivation and details see the https://github.com/m-m-m/ui-api/wiki[wiki] or JavaDoc (click on the badgets below).
In order to implement your client (with UI) you only need to depend on modules from this API.
Therefore, you will typically build a module for your client that is portable.
Dependencies to the implementation of this UI are only needed at runtime.
You can create modules for each toolkit or technology you want support for your client where you add the dependency to the specific implementation and just one or few classes to bind and launch the client. Details how to do that can be found in the documentation of the actual UI implementation or you can have a look at our https://github.com/m-m-m/ui-demo[ui-demo].

=== Overview

* link:doc/README.adoc[documentation] (with all overview diagrams)
* link:core/README.adoc[mmm-ui-api-core] (fundamentals and base widgets)
* link:tab/README.adoc[mmm-ui-api-tab] (tabbed panel to show sub-dialogs in tabs)
* link:number/README.adoc[mmm-ui-api-number] (all kind of numeric input widgets)
* link:temporal/README.adoc[mmm-ui-api-temporal] (input widgets for date and time)
* link:window/README.adoc[mmm-ui-api-window] (windows and popups)
* link:menu/README.adoc[mmm-ui-api-menu] (menu-bar and navigation-bar)
* link:data/README.adoc[mmm-ui-api-data] (widgets to display datasets as tables and trees)
* link:chart/README.adoc[mmm-ui-api-chart] (widgets to visualize data as charts)
* link:form/README.adoc[mmm-ui-api-form] (widgets for forms to edit data)
* link:format/README.adoc[mmm-ui-api-format] (widgets for structured formats such as source-code viewer or HTML editor)
* link:breadcrumb/README.adoc[mmm-ui-api-breadcrumb] (breadcrumb bar)
* link:media/README.adoc[mmm-ui-api-media] (audio/video player)
* link:controller/README.adoc[mmm-ui-api-controller] (controllers and navigation)
* link:binding/README.adoc[mmm-ui-api-binding] (powerful data-binding)
